copy to ~/.autowzk for local images too, fix compton issue

diff --git a/autowzk b/autowzk
--- a/autowzk
+++ b/autowzk
@@ -21,7 +21,7 @@ usage() {
   exit 1
 }
 
-IMG_DL=~/.autowzk
+SRC=~/.autowzk
 
 declare -A COLORS
 COLORS=(
@@ -64,10 +64,9 @@ EOM
 if [ ! -f "$1" ]; then
   [[ "$1" != http* ]] && usage
 
-  curl "$1" -o "$IMG_DL" 2>/dev/null || (echo "URL invalid." && exit 1)
-  img="$IMG_DL"
+  curl "$1" -o "$SRC" 2>/dev/null || (echo "URL invalid." && exit 1)
 else
-  img="$1"
+  cp "$1" "$SRC"
 fi
 
 if [ -z "$2" ]; then
@@ -88,7 +87,7 @@ fi
 echo "Using primary=$primary, secondary=$secondary..."
 echo
 
-colors="$(colorz2 --no-preview -n 6 "$img")"
+colors="$(colorz2 --no-preview -n 6 "$SRC")"
 [ "${PIPESTATUS[0]}" -ne 0 ] && exit 1
 
 primaries="$(echo "$colors" | sed -n "$((primary - 1))p")"
@@ -97,7 +96,7 @@ yaml="$(echo \
   "$colors" "$primaries" \
   "${COLORS[$primary]}" "${COLORS[$secondary]}" \
   "$primary"            "$secondary" |\
-  xargs printf "$TEMPLATE" "$(readlink -f "$img")")"
+  xargs printf "$TEMPLATE" "$(readlink -f "$SRC")")"
 
 echo "Generated YAML:"
 echo "$yaml"
