Fix some error cases.

diff --git a/gitlab-artifacts b/gitlab-artifacts
--- a/gitlab-artifacts
+++ b/gitlab-artifacts
@@ -7,15 +7,22 @@
 #
 # Author: metakirby5
 
+log() {
+  echo "$@" >/dev/stderr
+}
+
+fail() {
+  log "$@"
+  exit 1
+}
+
 checkdep() {
   which "$1" &>/dev/null || echo " $1"
 }
 
 missing="$(checkdep urlencode)$(checkdep curl)"
-if [ "$missing" ]; then
-  echo "The following dependencies are missing:$missing"
-  exit 1
-fi
+[ "$missing" ] && fail "The following dependencies are missing:$missing"
+[ -z "$GITLAB_TOKEN" ] && fail 'Missing $GITLAB_TOKEN!'
 
 usage() {
   echo "Usage: $(basename "$0") [job URL] [output filename]"
diff --git a/gitlab-install b/gitlab-install
--- a/gitlab-install
+++ b/gitlab-install
@@ -3,18 +3,26 @@
 # https://gitlab.domain.com/user/project/-/jobs/12345
 #
 # Dependencies: mktemp, unzip, adb, gitlab-artifacts
+# Environment variables: $GITLAB_TOKEN
 #
 # Author: metakirby5
+
+log() {
+  echo "$@" >/dev/stderr
+}
+
+fail() {
+  log "$@"
+  exit 1
+}
 
 checkdep() {
   which "$1" &>/dev/null || echo " $1"
 }
 
 missing="$(checkdep mktemp)$(checkdep unzip)$(checkdep adb)$(checkdep gitlab-artifacts)"
-if [ "$missing" ]; then
-  echo "The following dependencies are missing:$missing"
-  exit 1
-fi
+[ "$missing" ] && fail "The following dependencies are missing:$missing"
+[ -z "$GITLAB_TOKEN" ] && fail 'Missing $GITLAB_TOKEN!'
 
 usage() {
   echo "Usage: $(basename "$0") [job URL] (name pattern) (installer...)"
@@ -23,10 +31,9 @@ usage() {
 }
 
 [ "$#" -lt 1 ] && usage
-job="$1"
-shift
-name_pat="$1"
-shift
+
+job="$1"; shift
+name_pat="$1"; shift
 
 artifacts="$(mktemp).zip"
 artifacts_dir="$(mktemp)_extracted"
